### ISSUE TITLE
How to include NMS in ONNX ?

### ISSUE THREAD

**Issue by AmrElsersy** [SchweizerischeBundesbahnen/sbb-ml-models#12]
Hi, I want to deploy the model on react-native in javascript, so I need to export it with ONNX.

But the original export functionalities dosn't combine the NMS with it, how can I include it to ONNX ? 
Thanks

**Comment by fleuryj** [comment]
Hello @AmrElsersy !
In order to include NMS in the ONNX model, you can first add it to the PyTorch model, before converting it to ONNX.
I've provided an example in the branch [feature/onnx](https://github.com/SchweizerischeBundesbahnen/sbb-ml-models/tree/feature/onnx/converter) .
In the [ONNX converter](https://github.com/SchweizerischeBundesbahnen/sbb-ml-models/blob/feature/onnx/converter/onnx/onnx_converter/pytorch_to_onnx_converter.py), we first load Yolov5 PyTorch model, then add NMS and normalization to it. After that, we convert it ONNX and add the metadata.
I've also provided an inference example (to check that the conversion went okay).
The converted ONNX model has three outputs: location (yxyx coordinates for each detection), category (index of detected category) and score (confidence score for each detection). The labels for the model are stored in the metadata under the key labels ([more info](https://github.com/SchweizerischeBundesbahnen/sbb-ml-models/blob/feature/onnx/converter/ONNXConversion.md)).
