### ISSUE TITLE
Usage of ios and android libraries for custom object detector yolov7 models

### ISSUE THREAD

**Issue by Sri20021** [SchweizerischeBundesbahnen/sbb-ml-models#7]
Hello,

Thanks for sharing the object detector repos for ios and android and making it open source. My question is regarding the usage of these libraries for custom yolov7 model. Could you please let me know what all changes need to be made to get it running. A few things that I noted till now are as follows: labels.txt is not available in my custom made tflite model, metadate information such as confidence threshold, IoU threshold, resolution, etc, not available in the tflite model.

Please let me know what changes need to be made to have the converted model seamlessly work in the optimized ios and android deployment frameworks.

Thanks,
Srinivas

**Comment by fleuryj** [comment]
Hello,

I am not sure I've understood your question correctly: you have tried this out and the converted model does not contain all required metadata ? Or you tried it and it fails, and it could be due to the difference in metadata between Yolov5 and Yolov7 ?

**Comment by Sri20021** [comment]
Thanks @fleuryj  for the response. Yes, I initially tried converting yolov7 model to tflite model using this repo. However, it failed. Therefore, I converted the custom yolov7 model to tflite through pytorch -> onnx -> tensorflow -> tflite path using customary approach. In this case, I am able to run the model inferencing by adding pre-processing (BGR to RGB; normalization of RGB values from (0,255) to (0,1)) and post-processing steps (results are parsed into the required information such as bounding box, class number, confidence score, etc) in Python. However, when I try the same model running using the SBB-ML Android repo (https://github.com/SchweizerischeBundesbahnen/sbb-ml-android), I am getting various exceptions and finding it hard to fix them. I guess all the pre-processing and post-processing steps are included in the SBB-ML Android repo.

It is in this regard, I wanted to know what all metadata needs to be added to the tflite model converted from Pytorch yolov7 model so that I could use your repo for inferencing in Android (and iOS) platforms. In other words, if this repo (sbb-ml-models) can also provide code to convert pytorch yolov7 to tflite model, it would be very helpful. 

Thanks again,
Srinivas

**Comment by fleuryj** [comment]
Hello @Sri20021,

Checkout the new branch [feature/yolov7](https://github.com/SchweizerischeBundesbahnen/sbb-ml-models/tree/feature/yolov7). You can convert now a Yolov7 model to TFLite using this repo - it will then be completely compatible with the Android library (iOS not done yet, as there are some limitations from CoreML - would take more time to find a workaround, I might get around to it someday, but it is not a priority). 
If you do get some error (`NameError: name 'SomeModule' is not defined`), it means that the PyTorch module 'SomeModule', defined in `yolov7/models/common.py` does not have a counterpart in Tensorflow `yolov7/models/tf.py`: you only need to import said module into the `tf.py` file and implement it in Keras (with the additional parameters w=None, which are the weights and used to initialize the Keras model with the same weights at the PyTorch one). Or easier, just reach out once again!

To install the converter, take a look at [How to install the converter](https://github.com/SchweizerischeBundesbahnen/sbb-ml-models/tree/main/yolov5-coreml-tflite-converter#conversion); with an additional step (2):
1) run `./install.sh` script to install all dependencies
2) run `./use_yolov7.sh` script (e.g. models and utils from Yolov7 will be used, instead of the ones from Yolov5)
3) 'pipenv shell' to activate the pipenv environment
4) ready to convert a model with `python tflite/convert.py --model YourModel.pt --output-name YourConvertedModel`

Note: I have seen that some Yolov7 are quite big, be aware that the bigger the slower it will run on Android and if it is too big, it won't be supported / the app will crash.
Let me know if it works for you, I have only tested it with a version of the Yolov7 model.
Best,
Jeanne

**Comment by Sri20021** [comment]
Thanks @fleuryj  for the detailed response.
